### ISSUE TITLE
osmdata and leaflet

### ISSUE THREAD

**Issue by RoyalTS** [ropensci/osmdata#100]
Something that is related to https://github.com/r-spatial/mapview/issues/85 and seems wrong:

    library(dplyr)
    library(sf)
    library(osmdata)
    library(leaflet)
    
    query_string <- '
    [out:xml];
    area["name"="Alabama"]->.boundaryarea;
    (
      node["leisure"="park"](area.boundaryarea);
      way["leisure"="park"](area.boundaryarea);
      relation["leisure"="park"](area.boundaryarea);
    );
    (._;>);
    out body;'
      
    al_parks <- osmdata_sf(query_string)
    
    al_parks$osm_polygons %>%
      head(1) %>%
      leaflet %>%
      addTiles %>%
      addPolygons()
    # doesn't work
    
    names(al_parks$osm_polygons$geometry) <- NULL
    
    al_parks$osm_polygons %>%
      head(1) %>%
      leaflet %>%
      addTiles %>%
      addPolygons()
    # works

**Comment by mpadge** [comment]
Yeah, you're definitely right that something's wrong there. To give a short answer: Simple Features is far from a perfect solution in many ways, and there is work afoot for a more flexible implementation starting from [`silicate`](https://github.com/hypertidy/silicate). The OGC simply never envisioned that (simple) features might or could themselves have names, while OpenStreetMap is entirely built around hierarchical inter-references through names of all objects. The two are in many ways not very compatible (see [`osmdata` 2nd vignette](https://ropensci.github.io/osmdata/articles/osm-sf-translation.html) for details if you're interested).

The reason the first code doesn't work is definitely because of `leaflet/mapview` not envisioning that geometrical features could have names, as indicating in the referenced issue. An easy work-around is to repeat the first couple of lines of code of the current [`leaflet_sfc()` fn](https://github.com/r-spatial/mapview/blob/develop/R/sf.R) (the `if(!is.null(names(x)))` bit) in `leaflet_sf()` as well, but that ought not be necessary! The whole thing should just work with named objects! I'd send a PR, but I really don't know where and how `mapview` interfaces with `leaflet` at that point, and the solution is really ... a major overhaul of the way geometric objects ("features", if you like) are stored.

Setting names to `NULL` simply removes very useful information of the kind not envisioned by Simple Features (and the `sf` package simply inherits this oversight, so it's not to blame here). It's obviously useful to click on a feature and find out **what it's called!**, yet this is prohibited by SF (or it's expected that a field will hold the "name", rather than the entire features themselves being named). A satisfactory solution for this is nevertheless a long way off, so i'll just close this issue if that's okay with you.

(And this is likely a unique `osmdata` issue, because `osmdata` implements its own modified version of `sf` that stores the names of all objects. Because these were never envision by Simple Features, `sf` itself just ignores them, which is useful until other code actually expects there to be no names. Fault then lays not at `osmdata` for retaining and inter-referencing really useful **named objects**, but in Simple Features itself for not "permitting" named objects.)

Thanks for raising this important issue, and if you're really keen to help resolve these kinds of deeper issues of spatial representation, head over to [`hypertidy`](https://github.com/hypertidy) and chip in there!
cc @mdsumner
