### ISSUE TITLE
Timeout error keeps happening

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#101]
First of all, I think this is more of a question due to my lack of understanding of `timeout` and `memsize` parameters, rather than an actual bug report.
Previous to commit fad4c0cc900b693b62516cdf1fbfedb6326297cf I never encountered any timeout when executing even large queries (e.g. list of amenities in an entire city).
After that, even when providing big values for timeout and memsize as parameters to `osmdata::opq()` (1e6, as an order of magnitude) I obtain very often the following error:

```
Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: runtime error: open64: 0 Success /osm3s_v0.7.54_osm_base Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request.
```

Maybe I am missing something obvious, otherwise let me know if you need a reproducible example.

**Comment by fzenoni** [comment]
I've just realized that removing the parameters, hence accepting the default behavior, make things much smoother.
What happens then? How come a timeout of 25 (I guess ms) makes things easier than one million?

**Comment by mpadge** [comment]
good question, and i have a suspicion: `overpass` really seems to be encountering some issues at the moment. The `osmdata` package now generally fails on travis because of `overpass` failures, and i just have to manually restart each build several times until it succeeds. Demand must have recently increased to some unexpectedly high level? Anyway, I guess what happens is that queries with long `timeout` values are given a lower priority on `overpass` because they're likely going to be large queries. This means increasing `timeout` is likely at the moment to actually increase the chances of a request failing. Just a guess, but it seems plausible to me.

This was also the reason that I recently ensured that the overpass messages are dumped in full to screen like the one you pasted above. At least we now know a bit about what's going on.
