### ISSUE TITLE
Way to use areas?

### ISSUE THREAD

**Issue by beingalink** [ropensci/osmdata#110]
Hi!

I'm trying to use areas with osmdata as I was using it with overpass-api.

Example:
area["de:regionalschluessel"~"^057"];
or
area["de:amtlicher_gemeindeschluessel"="08222000"];

I guess I need to derive a bbox from this query first? Is this possible?

And then how do I restrict add_osm_feature() to a defined area?

I hope this question isn't too stupid but I couldn't find any information on this.
Thanks for creating this package and all your work put into it!

**Comment by mpadge** [comment]
Thanks for the enquiry @beingalink. That's all pretty straightforward, you just need first to define a bounding box in `opq()` (or via `getbb()`). For "regionalschluessel", you can just use Deutschland:
```
dat <- opq ("deutschland") %>%
    add_osm_feature (key = "de:regionalschluessel", value = "^007", value_exact = FALSE) %>%
    osmdata_sf ()
```
The `value_exact = FALSE` parameter translates the overpass query to "~" instead of "=", and that gives you 59 polygons. Looking at all `"regionalschluessel"` suggests that only Bundesland#07 is actually present in OSM. For a `"gemeindeschluessel"`, you could use a Bundesland boundary. If you then want to extract features only within a polygonal boundary, you can use `trim_osmdata()`, first getting the polygon with, for example,
```
bp <- getbb ("nrw", format_out = "polygon") # yep, that works
dat <- trim_osmdata (dat, bb_poly = bp)
```
Let me know if you've got any further Qs.
```

**Comment by beingalink** [comment]
Thanks for your help! When I try your example code, I get empty results.
```
dat <- opq ("deutschland") %>%
    add_osm_feature (key = "de:regionalschluessel", value = "^007", value_exact = FALSE) %>%
    osmdata_sf ()
```
results in:
```
Object of class 'osmdata' with:
                 $bbox : 49.469222,6.1122494,50.1298541,6.5312481
        $overpass_call : The call submitted to the overpass API
            $timestamp : [ Di 3 Dez 2017 06:03:20 ]
           $osm_points : 'sf' Simple Features Collection with 0 points
            $osm_lines : 'sf' Simple Features Collection with 0 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 0 polygons
       $osm_multilines : 'sf' Simple Features Collection with 0 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 0 multipolygons
```
My `osmdata` version is 0.0.5.

**Comment by mpadge** [comment]
oh sorry, should have been this:
```
dat <- opq ("deutschland") %>%
    add_osm_feature (key = "de:regionalschluessel", value = "^07", value_exact = FALSE) %>%
    osmdata_sf ()
```
With `value = "^07"`, not `value = "^007"` - there are no `"^007"` values.
