### ISSUE TITLE
Missing data in osmdata_pbf

### ISSUE THREAD

**Issue by gregmacfarlane** [ropensci/osmdata#122]
I'm having a difficult time using the `osmdata_pbf` function to get a `.pbf` file of highway networks surrounding Athens, GA.

```r
query <- opq ("athens georgia USA") %>%
  osmdata::add_osm_feature(
    key = 'highway',
    value = 'motorway|motorway-link|trunk|primary|secondary|tertiary',
    value_exact = FALSE)
```

The simple features download seems fine, with the appropriate number of features, etc.

```r
sf <- osmdata_sf(query)
sf

## Object of class 'osmdata' with:
##              $bbox : 33.7950905,-83.5481868,34.1150905,-83.2281868
##     $overpass_call : The call submitted to the overpass API
##         $timestamp : [ Mon 2 Feb 2018 13:38:03 ]
##        $osm_points : 'sf' Simple Features Collection with 18518 points
##         $osm_lines : 'sf' Simple Features Collection with 881 linestrings
##      $osm_polygons : 'sf' Simple Features Collection with 1 polygons
##    $osm_multilines : 'sf' Simple Features Collection with 0 multilinestrings
## $osm_multipolygons : 'sf' Simple Features Collection with 0 multipolygons
```

The XML download also works, with a file of the appropriate size that I can do some other things with. The PBF file, on the other hand, seems pretty small (even for a compressed format). Beyond that, the resulting file is unreadable by QGIS or Conveyal's [R5](https://github.com/conveyal/r5) routing engine.

```r
osmdata_xml(query, "data.xml") # 2MB
osmdata_pbf(query, "data.pbf") # 574.5 KB
```

Do I need to wait for #74 to finish? Or is there something else I'm missing?

**Comment by mpadge** [comment]
Thanks Greg, and sorry to report, but you'll have to wait for `osmdata_pbf` to be properly implemented. This mostly just requires adding dependency on the [`RProtoBuf` package](https://cran.r-project.org/package=RProtoBuf), but that's a heavy dependency so we want to avoid it until absolutely necessary. The `osmdata_pbf()` call nevertheless returns the appropriate binary stream; it just needs to be serialized to be used. You could do this yourself pretty easily with the `RProtoBuf` package - see the [`quickref`](https://cran.r-project.org/web/packages/RProtoBuf/vignettes/RProtoBuf-quickref.pdf) and [`intro`](https://cran.r-project.org/web/packages/RProtoBuf/vignettes/RProtoBuf-intro.pdf) for hints. The necessary protocol buffer format file is [`osmformat.proto`](https://github.com/scrosby/OSM-binary/blob/master/src/osmformat.proto) which you have to submit to the `RProtoBuf::readProtoFiles()` call.

Having done that, you could read it back via `sf::st_read()`, because GDAL does read OSM protocol buffer format. I'd be keen to hear how you get on, and feel free to shoot any further Q's our way.
