### ISSUE TITLE
trim_osmdata() -  argument is zero length

### ISSUE THREAD

**Issue by prokulski** [ropensci/osmdata#137]
I've code like this:

```
data_sf <- getbb("Kraków, Poland") %>%
    opq() %>%
    add_osm_feature(key = "route", value = "bicycle") %>%
    osmdata_sf()
```

At this moment everything workes fine, but data_sf$osm_lines has lines not only around Cracow (Poland) but also around Wien (Austria). Try to plot this data_sf - You'll see.

So, I tried to "cut" them a little:

`data_sf <- trim_osmdata(data_sf, getbb("Kraków, Poland", format_out = "polygon"))`

And I have error:

`Error 'if (nrow(bb_poly) > 2) {':argument is zero length`

If you'll use some location without polish characters sometimes this cutting works fine ("Wetlina, Poland" for example), some time it doen't ("Radom, Poland").

**Comment by mpadge** [comment]
Oh that's really interesting, thanks! I'll dig into it asap

**Comment by mpadge** [comment]
Thanks for the prompt to insert an important check. You should now see this:
```
> data_sf <- trim_osmdata(data_sf, getbb("Kraków, Poland", format_out = "polygon"))
# bb_poly has more than one polygon; the first will be selected.
```
and it should deliver the desired result. `getbb(..., format_out = "polygon")` can deliver an arbitrary number of polygons, but previous code prior to that commit presumed one particular one to have been (manually) pre-selected. This is now done automatically by selecting the first.

Regarding the geographic extent of the lines, that is simply because the query returns the entirety of any bicycle route that partly traverses the defined bounding box. These may well include long distance routes, so in this case one international route connects Cracow with Wien. Note, however, that `trim_osmdata` won't really fix this issue for you, because it will simply remove (`exclude = TRUE`) the entirety of those components which extend beyond the bounding box. This an intentional design feature to ensure that `osmdata` delivers data which remain true to the original data from Open Street Map, as well as to Simple Features (`sf`). The kind of trimming you desire would require dissecting individual features, resulting in something that differed from the actual data as represented by OSM.

The most effective way to deal with such cases is to control the lon-lat limits of your plot, so these very long lines simply won't appear. This can be very easily done with [`osmplotr`](https://github.com/ropensci/osmplotr), but is a bit fiddlier to achieve with default `sf` plotting options.

**Comment by prokulski** [comment]
Thanks for comment. I'll check (install from github gives this version?) tommorow, but I tried with

`trim_osmdata(data_sf, getbb("Kraków, Poland", format_out = "polygon")[[1]])`

(and [[2]] and so on) and there was some error (don't remember exacly)

**Comment by prokulski** [comment]
Still not good :/ I've done following steps:

```
devtools::install_github('osmdatar/osmdata')

packageVersion("osmdata")
[1] ‘0.0.7.1’
```

and then used my function:

```
getOSMData <- function(f_localisation, f_key, f_value) {
  data_sf <- getbb(f_localisation) %>%
    opq() %>%
    add_osm_feature(key = f_key, value = f_value) %>%
    osmdata_sf()

  return(data_sf)
}
```

to get data:

```
krakow <- c(getOSMData("Kraków, Poland", "route", "bicycle"),
getOSMData("Kraków, Poland", "highway", "cycleway"))
```

works fine - see map:

```
# helpful functions
getLngLat <- function(f_data_sf) {
  gps_coords <- f_data_sf$bbox %>%
    str_split(",") %>%
    unlist() %>%
    as.numeric()
  
  lng_coord <- (gps_coords[2] + gps_coords[4])/2
  lat_coord <- (gps_coords[1] + gps_coords[3])/2
  
  return(list(lng = lng_coord, lat = lat_coord))
}

plotLeafletMap_lines <- function(f_data_sf) {
  # workaround via https://github.com/ropensci/osmdata/issues/100
  names(f_data_sf$osm_lines$geometry) <- NULL
  
  gps_coords <- getLngLat(f_data_sf)
  
  leaflet() %>%
    addTiles() %>%
    setView(lng = gps_coords$lng, lat = gps_coords$lat, zoom = 11) %>%
    addPolylines(data = f_data_sf$osm_lines,
                 color = 'red')
}

# plot map
plotLeafletMap_lines(krakow)
```

Try to trim data:

```
krakow2 <- trim_osmdata(krakow, getbb("Kraków, Poland", format_out = "polygon"))
```

And what I got:

```
bb_poly has more than one polygon; the first will be selected.
Error in if (nrow(dat[[g]]) > 0) { : argument is of length zero
```

**Comment by mpadge** [comment]
That is now because of a non-UTF encoding issue (in "Kraków"). Let me examine further

**Comment by mpadge** [comment]
All seems okay to me. Your error that `argument is of length zero` indicates that `dat[[g]]` is unexpectedly empty, in turn indicating that this may simply be an API failure. The overpass API sometimes simply fails to return data, yet does not issue any errors. Try re-installing, check that you now get
```
packageVersion("osmdata")
[1] ‘0.0.7.2’
```
and it should work.
