### ISSUE TITLE
turn data into igraph?

### ISSUE THREAD

**Issue by waholulu** [ropensci/osmdata#142]
Is there anyway to turn the data downloaded into igraph format, like what the "osmar" package can do?

**Comment by mpadge** [comment]
Easily done via the [`dodgr` package](https://github.com/ATFutures/dodgr), which includes example OSM data called "hampi":
```
library(osmdata)
library(dodgr)
dat <- weight_streetnet (hampi) [, c ("from_id", "to_id", "d")] 
ig <- igraph::make_graph (as.vector (rbind (dat$from_id, dat$to_id)), directed = TRUE)
igraph::E(ig)$weight <- dat$d
```
The `dodgr::weight_streetnet()` function converts an `sf::LINESTRING` object into a simple `data.frame` containing all individual edges and corresponding (`from`->`to`) vertex IDs. The `igraph` constructed above (`ig`) is then reduced to just vertex IDs and edge distances.

I don't see this functionality having a place in `osmdata` itself, because it is specific to street networks only, whereas `osmdata` really is intended to be entirely general. The corresponding issue in `dodgr` is [here](https://github.com/ATFutures/dodgr/issues/39) - feel free to add any thoughts or wishes in terms of `igraph` conversion in that issue. Thanks!

**Comment by mpadge** [comment]
Update: `dodgr` now has `dodgr_to_igraph()` function, so you can do:
```
dat <- osmdata_sf (...)
net <- weight_streetnet(dat$osm_lines) %>% dodgr_to_igraph()
```
