### ISSUE TITLE
how to increase memsize?

### ISSUE THREAD

**Issue by morellek** [ropensci/osmdata#147]
Dear osmdata developers,

I wanted to ask you how one can increase memsize parameter? I indeed face following error message when running my query:

opq(c(23.32875, 23.98439, 52.6549, 53.582)) %>% 
  add_osm_feature(key = 'highway',  value ='primary') %>% 
  osmdata_sp() %>%  `[[`("osm_lines")

Error in check_for_error(doc) : General overpass server error; returned:
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL. runtime error: Query ran out of memory in "query" at line 4. It would need at least 529 MB of RAM to continue. 

 I couldn't find any info about it and all my attemps (simply addind argument memsize=1000 e.g. in opq function) failed. I would be happy for your support.
Thank you for your work.

**Comment by Robinlovelace** [comment]
Thanks for posting the question here following previous correspondence. As documented in #97 setting the `memsize` argument in `opq()` calls can solve the direct issue. On the wider issue of importing large amounts of data from OSM: I suggest downloading data from a service such as https://www.geofabrik.de/data/download.html or, if you have the hardware/skills extracting the data from a planet.osm dump, as documented here: https://wiki.openstreetmap.org/wiki/Planet.osm

**Comment by mpadge** [comment]
This question via email prompted [this tweak to `opq` documentation](https://github.com/ropensci/osmdata/commit/9adf56697fd36ac9348a6e80ae23aea6aa7bae12), and the realisation that the large amount of data requested forced a trade-off between data being too big for overpass (e.g. using `memsize = 2e9)`, or being big enough but taking too long and timing out (e.g. using `memsize = 4e9`). Either way, overpass errors and the data aren't returned, leaving the only option as planet files and `osmium`. 

This is also related to #74, which will enable `osmdata` to directly import planet files. Until that time, these can only be processed with `osmium` and `sf`, which are not optimal within **R** because the OSM IDs of the geometry components get stripped off by GDAL.

**Comment by Robinlovelace** [comment]
Shows how just asking a question can be useful: thanks @morellek for asking the question and indirectly improving the documentation for the the benefit of everyone!
