### ISSUE TITLE
silicate compliance 

### ISSUE THREAD

**Issue by mdsumner** [ropensci/osmdata#150]
An issue from me changing silicate, I renamed `.vertex0` and `.vertex1` to .`vx0` and `.vx1`

I.e., my wokaround example

```R
library(osmdata)
dat <- opq ("london uk") %>%
  add_osm_feature (key = "name", value = "Thames", value_exact = FALSE) %>%
  osmdata_sc()

library(silicate) ## devtools::install_github("hypertidy/silicate@topology")
names(dat$edge)[1:2] <- c(".vx0", ".vx1")
plot(dat)  ## all good!
```

The `$meta` is also not right, mine is a tibble with proj and ctime, not an attribute. Totally open to advice on that!  (It currently only affects printing)

**Comment by mpadge** [comment]
That implements changes to `$vertex` table naming. The `meta` stuff can wait for now, I thought, because it's got a time, but not really `ctime` - it's actually the time at which the OSM doc was generated by `overpass`, which may differ from the time at which `osmdata_sc()` (or whatever) was actually called. So I'm still uncertain about what to do there. But yeah, I should `tibble`-ise it. Any particular reason why you call it `ctime`? All other `osmdata_XX()` functions how have a `$meta` list item which has `$meta$timestamp`. I like timestamp in that context. If you do `SC(x)`, will `ctime` be inherited from `x` (where that is possible), or will `ctime` always just reflect time of implementing `SC(x)`?

**Comment by mdsumner** [comment]
I was copying `file.info` :)     I've never actually used the ctime, but I like the idea of recording changes - particularly I wanted to record a sequence of projection changes (I've never formally applied that except in `anglr::globe` and `anglr::reproject`.)

**Comment by mdsumner** [comment]
Very good now!  This is going to be very interesting

**Comment by mpadge** [comment]
metadata fixed with that commit - I've just called it `ctime` for now; details can all be worked out later.

**Comment by mdsumner** [comment]
woohoo!  I got my OSM game on 

![image](https://user-images.githubusercontent.com/4107631/47717091-dc105e00-dc98-11e8-8fb1-72446f5c2b40.png)

**Comment by mdsumner** [comment]
So this already works (filter.SC is not exported): 

```R

plot(filter(dat, key == "maxspeed" &  value > 50))

```
![image](https://user-images.githubusercontent.com/4107631/47717544-27773c00-dc9a-11e8-861f-c2a162201184.png)

See the vertices are all plotted, and they aren't currently culled by the filter (it's a non-simple join, but I also like the idea of vertices being sacrosanct - or even back-ended in storage). 

But, I had to `dat$object$object_ <- dat$object$id` 

Which brings me to the wonderful topic of *naming things*. As you've seen I've changed internal conventions several times, but do we want to take *native labels* like the OSM id, and map that to the names used in silicate?

**Comment by mpadge** [comment]
And that filter example is amazing - it really works just like that? Wow! I won't get to actually play until getting onto [`SC->dodgr`](https://github.com/ATFutures/dodgr/issues/64) ... which is now free to leap ahead at similar pace :bike: Then I'll really be in a position to take it for a spin

**Comment by mpadge** [comment]
That commit renames first col of `$object` from `$object$id` to `$object$object_` (I forgot to escape the `$` signs in the commit message)
