### ISSUE TITLE
Error in extract_osm_bojects: Could not convert using R function: as.data.frame

### ISSUE THREAD

**Issue by Tazinho** [ropensci/osmdata#160]
I am trying to get some data for Dortmund. For Hamburg and Meppen it works. However, for Dortmund I am getting always these error. Any idea?

```r
> bbox <- get_bbox (osmdata::getbb("Dortmund"))
> dat_b <- extract_osm_objects (key = 'building', bbox = bbox)
add_feature() is deprecated; please use add_osm_feature()
Error in rcpp_osmdata_sf(doc) : 
  Could not convert using R function: as.data.frame.
```

**Comment by mpadge** [comment]
I think the problem here is simply that the data you're requested are too large:
```
library(osmdata)
> q <- opq("Dortmund") %>%
      add_osm_feature (key = "building")
> osmdata_xml (q, filename = "dortmund.osm")
> format (file.size ("dortmund.osm"), big.mark = ",")
[1] "311,134,591"
```
You're asking to process 1/3 GB of data **in memory** which will often simply lead to unpredictable results. On my machine, this simply kills the R session. In cases like this, it is strongly advisable to break your enormous queries down into more manageable subsets. This is typically approached by requesting specific values. For buildings, the largest number usually just has `key = "building", value = "yes"`, but in this case that's still 250MB of building data, which still kills my computer.

I would suggest here that you'd be best off getting the bounding box and dividing that into chunks. Having got each bit, you can then use the `osmdata::c()` operation to join all the bits together and automatically include only unique objects:
```
mydat <- c (mydat1, mydat2, mydat3, mydat4)
```
Given your claim that Hamburg works, this clearly reveals one conclusion: Dortmund is ~~better~~bigger than Hamburg!

**Comment by Tazinho** [comment]
Great! Thanks for diving into this. I followed your workaround and can now download the data.

I wrote a small function to streamline this, see below. Maybe it's useful :)

However, I got another issue when combining the data via `osmdata::c()` (see the follow up issue).

``` r
get_bboxes <- function(bbox, x = 1L, y = 1L){
  
  stopifnot(identical(dim(bbox), c(2L, 2L)))
  
  x_points <- seq(bbox[1,1], bbox[1,2], length.out = x + 1L)
  y_points <- seq(bbox[2,1], bbox[2,2], length.out = y + 1L)
  
  bboxes <- vector("list", x * y)
  
  counter <- 1L
  
  for (i in seq_len(x)) {
    for (j in seq_len(y)) {
      bboxes[[counter]] <- 
        matrix(c(x_points[i ]  , y_points[j],
                 x_points[i+1L], y_points[j+1L]), 
               nrow = 2,
               dimnames = list(c("x", "y"), 
                               c("min" ,"max")))
      counter <- counter + 1L
    }
  }
  
  bboxes
}

library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
library(osmplotr)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright

get_bbox (osmdata::getbb("Dortmund"))
#>         min       max
#> x  7.305279  7.625279
#> y 51.354227 51.674227

get_bboxes(osmdata::getbb("Dortmund"))
#> [[1]]
#>         min       max
#> x  7.305279  7.625279
#> y 51.354227 51.674227
get_bboxes(osmdata::getbb("Dortmund"), 2, 2)
#> [[1]]
#>         min       max
#> x  7.305279  7.465279
#> y 51.354227 51.514227
#> 
#> [[2]]
#>         min       max
#> x  7.305279  7.465279
#> y 51.514227 51.674227
#> 
#> [[3]]
#>         min       max
#> x  7.465279  7.625279
#> y 51.354227 51.514227
#> 
#> [[4]]
#>         min       max
#> x  7.465279  7.625279
#> y 51.514227 51.674227
```

Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)
