### ISSUE TITLE
How to invoke `osmdata::c()` correctly

### ISSUE THREAD

**Issue by Tazinho** [ropensci/osmdata#161]
As described in https://github.com/ropensci/osmdata/issues/160 I loaded data for several bounding boxes. I'ld like to combine these data into one object via the proposed `osmdata::c()`. I downloaded the neweset pkg-versions. However, it seems that I do sth. obviously wrong or there is no `osmdata::c()` provided?

``` r
# devtools::install_github("ropensci/osmdata", force = TRUE)
# devtools::install_github("ropensci/osmplotr", force = TRUE)

library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
library(osmplotr)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright

osmdata::c
#> Error: 'c' ist kein von 'namespace:osmdata' exportiertes Objekt
osmdata:::c
#> Error in get(name, envir = asNamespace(pkg), inherits = FALSE): Objekt 'c' nicht gefunden
osmplotr::c
#> Error: 'c' ist kein von 'namespace:osmplotr' exportiertes Objekt
osmplotr:::c
#> Error in get(name, envir = asNamespace(pkg), inherits = FALSE): Objekt 'c' nicht gefunden
```

Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

So when combining with `c()` as proposed in https://github.com/ropensci/osmdata/issues/160 `base::c()` doesn't find it and I guess the default method gets called which gives me a very long list, which doesn't help for further processing/visualisations with your package.

**Comment by mpadge** [comment]
This works:
```
b <- get_bboxes(osmdata::getbb("Dortmund"), 2, 2)
dat <- lapply (b, function (i) {
                   opq (bbox = i) %>%
                       add_osm_feature (key = "building") %>%
                       osmdata_sf (quiet = FALSE) })
```
That will give you a list of the four data sets corresponding to your bboxes which can then be reduced to a single object with
```
dat <- do.call (c, dat)
```
Because each item is an `osmdata` object, the `c` method automatically calls `osmdata::c`. 
This *might* work, but even if it does I reiterate here that this is **not** recommended procedure! You are attempting to combine four lists each with hundreds of millions of entries. The `osmdata::c` operator is non-trivial, so this will likely take a very, very long time, although more likely will still fail because you're still trying to aggregate gigabytes of data in memory.

You can try a single `c` aggregation with
```
dat12 <- c (dat[[1]], dat[[2]])
```
even that will likely take a *very* long time.

Note also that `c` is an internal method of `osmdata` (not `osmplotr`), and so you can't call it with `osmdata::c` (it is "kein exportiertes Object").
