### ISSUE TITLE
osmdata retrieves also nodes with missing key

### ISSUE THREAD

**Issue by slow-data** [ropensci/osmdata#163]
Hi,

I am trying to retrieve the all amenity=restaurant (nodes) in Madrid using osmdata. Using following code I get **4,867** nodes

```require(osmdata)

bb_mad <- getbb("Madrid") # Madrid bounding box from Nominatim API

restaurant_mad <- opq (bbox = bb_mad, timeout = 60) %>% 
  add_osm_feature("amenity", "restaurant") %>%
  osmdata_sf()

nrow(restaurant_mad$osm_points) 
```
Using overpass package (and also running directly in Overpass) I get **3,711** nodes. The code is the following 

```restaurant_opq_mad <- '[out:xml][timeout:100];
(
  node  ["amenity"="restaurant"] (40.3119774,-3.8889539,40.6437293,-3.5179163);
);
(._;>;);
out body;'

restaurant_mad2 <- overpass_query(restaurant_opq_mad)
nrow(restaurant_mad2@data)
```
I noticed the difference is due to osmdata extracting **1,156** extra nodes with "amenity" tag missing and "name" also missing. 

Do you know why there is this difference in the returned object?

**Comment by mpadge** [comment]
Thanks for the query. The difference is simply because `osmdata` returns **all** elements of **all** objects tagged `"amenity" = "restaurant"`. In your case, that is 124 polygons and 1 linestring as well as the points. All of the points that comprise those polygons and that linestring are then also included in `$osm_points`. This is an intentional part of the design because it allows, for example, direct analysis of all points that make up any other types of objects.

The short answer to your query is the `unique_osmdata()` function:
```
> bb_mad <- getbb("Madrid") # Madrid bounding box from Nominatim API
> restaurant_mad <- opq (bbox = bb_mad, timeout = 60) %>%
+       add_osm_feature("amenity", "restaurant") %>%
+         osmdata_sf()
> unique_osmdata(restaurant_mad)
Object of class 'osmdata' with:                                                                                                                                              
                 $bbox : 40.3119774,-3.8889539,40.6437293,-3.5179163                                                                                                         
        $overpass_call : The call submitted to the overpass API                                                                                                              
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 3711 points
            $osm_lines : 'sf' Simple Features Collection with 1 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 124 polygons
       $osm_multilines : NULL
    $osm_multipolygons : NULL
```
The `unique_osmdata` function returns only those components of each type (points, linestrings, etc) that are unique to that type.

**Comment by slow-data** [comment]
Thanks a lot for your answer. 

This means that in my case the "extra" 1,156 nodes are the nodes componing the polygons tagged as amenity=restaurant?

**Comment by mpadge** [comment]
Yep, exactly
