### ISSUE TITLE
Example failing for getbb example

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmdata#164]
``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
getbb("Hereford", display_name_contains = "United States", silent = FALSE)
#> [1] "https://nominatim.openstreetmap.org/?q=Hereford&featuretype=settlement&format=json&limit=10"
#> Error in getbb("Hereford", display_name_contains = "United States", silent = FALSE): No locations include display name United States
```

<sup>Created on 2019-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mpadge** [comment]
Yeah, I've recently had to fix some of the other examples with `display_name_contains` too. I guess these are due to OSM edits? Either way, I fixed the others by just replacing
```
getbb("Hereford", display_name_contains = "United States")
```
with
```
getbb("Hereford USA")
```
see, for example, [this commit](https://github.com/ropensci/osmdata/commit/02e3751507cefc97329c6ed1819362acc7b53aea)

**Comment by Robinlovelace** [comment]
Fixed in branch just merged.
