### ISSUE TITLE
Opq() to accept getbb(...,output_type="polygon")

### ISSUE THREAD

**Issue by mroorda** [ropensci/osmdata#166]
Currently, the `opq()` function only accepts a bbox with 4 coordinates. `getbb()` allows for a polygonal output of a bbox, but opq only processes the first 4 values of the output of the `getbb()` function. Is there a way to use a polygonal bbox in the `opq()` function? If there isn't, I think it should be included. Thanks anyway for an awesome package!

**Comment by mpadge** [comment]
Yeah, I agree that that would be great, but unfortunately isn't possible because the overpass server itself only accepts rectangular bounding *boxes*. This limitation motivated the `trim_osmdata()` function, which trims the rectangular results back to within a defined polygon - see [the original issue](https://github.com/ropensci/osmdata/issues/80) and maybe [this supplementary one](https://github.com/ropensci/osmdata/issues/153).

**Comment by Robinlovelace** [comment]
I think this would be possible and worthwhile. Would be awesome and useful to many people if `opq()` accepted `sf` or even `silicate` spatial objects. It would be relatively easy for that object to be converted to a rectangular window, I think - would you be happy with that @mroorda ?

**Comment by mpadge** [comment]
Yeah, that's a good point - it would only have to copy-paste the code from #153, which does it for `trim_osmdata()`. Simply allow `opq()` to accept same args.

**Comment by mroorda** [comment]
Yes I think that would be a great feature to increase the flexibility for `opq()` queries. Thanks for the suggestion @Robinlovelace

**Comment by mpadge** [comment]
Took a while here, but this now works via #171, #172, and mostly the lines added to `getbb` in [this commit](https://github.com/ropensci/osmdata/commit/fabcf27cc78888c938b6e72872879a2fc23812b6)
