### ISSUE TITLE
Vignette not reproducible

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [ropensci/osmdata#172]
Hi

I am trying to reproduce one of the vignettes but I am getting an error.  It appears to be related to it being a polygon.  When I rerun it using a rectangular box I get the output fine.  
![OSM issue](https://user-images.githubusercontent.com/43342160/56352897-1a0e2980-61c8-11e9-89b0-1e08ee112c3e.png)

**Comment by mpadge** [comment]
Thanks for noting that - Open Street Map is a constantly changing thing, and the `getbb` call no longer returns any polygon at all, causing the whole thing to fail. I'll update asap to a working example. Good catch!

---

By the way, instead of pasting a screenshot, you can copy the code you've got to your clipboard, and then run:
``` r
reprex::reprex ()
```
That will fill your clipboard with the results of running it, which you can then just paste into github directly. See the [reprex package](https://github.com/tidyverse/reprex) for further details.
