### ISSUE TITLE
Doubts reading the vignettes

### ISSUE THREAD

**Issue by agila5** [ropensci/osmdata#186]
Hi, today I read the vignettes of thepackage and run the code but I still have some doubts. 

1.  When I run the code in the section 2.1 where you explain how to combine several features of OSM I get different results then yours. This is not surprising since you probably run those lines several months ago but there is still something that I cannot understand. This is the code: 

``` r
# packages
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright

# data
q <- opq(bbox = 'Kunming, China') %>%
  add_osm_feature(key = 'natural', value = 'water') %>%
  add_osm_feature(key = 'name:en', value = 'Dian', value_exact = FALSE)

dat1 <- opq(bbox = 'Kunming, China') %>%
  add_osm_feature(key = 'natural', value = 'water') %>%
  osmdata_sf ()
dat2 <- opq(bbox = 'Kunming, China') %>%
  add_osm_feature(key = 'name:en', value = 'Dian', value_exact = FALSE) %>%
  osmdata_sf ()
dat <- c (dat1, dat2)

unlist (lapply (osmdata_sf (q), nrow) [4:8])
#>         osm_lines      osm_polygons osm_multipolygons 
#>                 2                 1                 1
unlist (lapply (dat1, nrow) [4:8])
#>        osm_points         osm_lines      osm_polygons osm_multipolygons 
#>             49055               175               831                44
unlist (lapply (dat2, nrow) [4:8])
#>        osm_points         osm_lines      osm_polygons    osm_multilines 
#>              4131                44                 4                 1 
#> osm_multipolygons 
#>                 1
unlist (lapply (dat, nrow) [4:8])
#>        osm_points         osm_lines      osm_polygons osm_multipolygons 
#>             51112               217               834                44
```

<sup>Created on 2019-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There are two things that are not clear to me: a) how is it possible that when you add the two features with a logical AND (i.e. the `q` object) then the result is formed by 4 objects and no osm_point? Probably I don't get something because I was thinking that every point object stored in osm_points was also a point of the others lines/polygons (as you explain in section 3.2) so I don't see how the two features share a line and several polygons but no point; b) what happened to the osm_multiline object of `dat1` when you merged `dat1` and `dat2` with `c(dat1, dat2)`? Because when I print the output of `dat` I see no osm_multiline. 

2. There are some problems with the Sevilla example since this is what I get:

``` r
# packages
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright

# data
q1 <- opq('Sevilla') %>%
  add_osm_feature(key = 'highway', value = 'cycleway')
cway_sev <- osmdata_sf(q1)

q2 <- add_osm_feature(q1, key = 'bicycle', value = 'designated')
des_bike <- osmdata_sf(q2)
q3 <- add_osm_feature(q2, key = 'bridge', value = 'yes')
des_bike_and_bridge <- osmdata_sf(q3)
nrow(des_bike_and_bridge$osm_points)
#> NULL
nrow(des_bike_and_bridge$osm_lines)
#> NULL

q4 <- add_osm_feature(q1, key = 'bridge', value = 'yes')
bridge <- osmdata_sf(q4)
des_bike_or_bridge <- c(des_bike, bridge)
nrow(des_bike_or_bridge$osm_points)
#> [1] 13
nrow(des_bike_or_bridge$osm_lines)
#> [1] 34
```

<sup>Created on 2019-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Then again it's not surprising that I get different result then yours but I don't understand how it's possible that when I merge the results of `des_bike` and `des_bridge` I get more lines then points (this is probably related to doubt 1 and section 3.2 since I thought that lines should be like a subset of points). Moreover I don't get any feature now when I intersect them but this should not be a problem of the package or the vignette. I manually changed the `add_feature` function to `add_osm_feature` as in the PR. 

3. In section 3.2 you explain the reasons why osmdata is more appropriate than sf/gdal when dealing with OSM data and I think they could be summarized as: *"sf/gdal returns only those objects unique to each category of spatial object while osmdata includes all points regardless of whether or not these are represented in other spatial objects. Similarly, line objects in sf/GDAL exclude any lines that are part of other objects such as multipolygon or multiline objects."*. Then I run the following code:

``` r
# packages
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright

# save data
opq(bbox = 'Trentham, Australia') %>%
  add_osm_feature(key = 'name') %>%
  osmdata_xml(filename = 'trentham.osm')

# osmdata
osmdata_sf(opq(bbox = 'Trentham, Australia') %>%
             add_osm_feature(key = 'name'), "trentham.osm")
#> Object of class 'osmdata' with:
#>                  $bbox : -37.4300875,144.2863388,-37.3500875,144.3663388
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 8686 points
#>             $osm_lines : 'sf' Simple Features Collection with 323 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 42 polygons
#>        $osm_multilines : 'sf' Simple Features Collection with 1 multilinestrings
#>     $osm_multipolygons : 'sf' Simple Features Collection with 6 multipolygons

# sf
nrow(sf::st_read('trentham.osm', layer = 'lines', quiet = TRUE))
#> [1] 305
length(sf::st_read('trentham.osm', layer = 'multilinestrings', quiet = TRUE)$geometry[[1]])
#> [1] 15
```

<sup>Created on 2019-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

From the output of the osmdata representation of OSM data I can see that there are 323 linestrings but, while I read the same data with st_read there are only 320 linestrings. What did I do wrong? 

I hope my questions are clear otherwise I could clarify them. Anyway thank you very much for your efforts in developing this package.

**Comment by mpadge** [comment]
Thanks as always @agila5 for this really considered input, and apologies that it's taken me so long to get back to you. I'll try to go through your points in order here:

> a) how is it possible that when you add the two features with a logical AND (i.e. the q object) then the result is formed by 4 objects and no osm_point? Probably I don't get something because I was thinking that every point object stored in osm_points was also a point of the others lines/polygons (as you explain in section 3.2) so I don't see how the two features share a line and several polygons but no point; 

I'm not sure about that either, and what you see would indeed be correct if the points were not there ... but i also can not reproduce your output. When I run those lines, I see the points included in the output. I guess we can just hope that this was some kind of glitch on your side, and that when you re-run it you do indeed see the points there?

> b) what happened to the osm_multiline object of dat1 when you merged dat1 and dat2 with c(dat1, dat2)? Because when I print the output of dat I see no osm_multiline.

That is definitely a problem with the code:
``` r
library(osmdata)
dat1 <- opq(bbox = 'Kunming, China') %>%
  add_osm_feature(key = 'natural', value = 'water') %>%
  osmdata_sf ()
dat2 <- opq(bbox = 'Kunming, China') %>%
  add_osm_feature(key = 'name:en', value = 'Dian', value_exact = FALSE) %>%
  osmdata_sf ()
dat <- c (dat1, dat2)
nrow (dat1$osm_multilines); nrow (dat2$osm_multilines); nrow (dat$osm_multilines)
#> NULL
#> [1] 1
#> NULL
```

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The third of those should be the same as the second, and definitely **not** `NULL`. That seems like the `c` operator is just looking at the first entry, which is `NULL`, and so returning an overall result of `NULL` without examining the second, non-`NULL` entry. I'll fix that first before continuing here ...

**Comment by mpadge** [comment]
The above commit fixes that, so the `c` method now returns the `osm_multilines` object. I also updated all of the vignette output for the Sevilla examples.

> when I merge the results of des_bike and des_bridge I get more lines then points

I can't reproduce this, and now get the following output:
``` r
setwd("/data/mega/code/repos/ropensci/osmdata")
devtools::load_all (".", export_all = FALSE)
#> Loading osmdata
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
q1 <- opq('Sevilla') %>%
    add_osm_feature(key = 'highway', value = 'cycleway')
des_bike <- osmdata_sf(q1)
q2 <- add_osm_feature(q1, key = 'bridge', value = 'yes')
des_bike_and_bridge <- osmdata_sf(q2)
q2 <- opq('Sevilla') %>%
    add_osm_feature(key = 'bridge', value = 'yes')
bridge <- osmdata_sf(q2)
des_bike_or_bridge <- c(des_bike, bridge)
des_bike_or_bridge
#> Object of class 'osmdata' with:
#>                  $bbox : 37.3002036,-6.0329183,37.4529579,-5.8191571
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 9782 points
#>             $osm_lines : 'sf' Simple Features Collection with 1075 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 9 polygons
#>        $osm_multilines : NULL
#>     $osm_multipolygons : NULL
```

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
... so more points that lines, as should be. But yes, of course you are right that numbers of points should always be greater (or maybe equal to) numbers of lines. Hopefully that was also just some glitch that can no longer be reproduced.

----

And then to your final question about differences between `osmdata` and `sf::st_read`: In short, one ought not presume that they will give the same result. I get the following:

method | N lines | N multilines | N multipolygons
--- | --- | --- | ---
`osmdata` | 835 | 2 | 14
`sf::st_read` | 802 | 15 | 2

The resolution here comes from looking at the structure of the actual `xml` file. This contains 16 `relation` objects, so the total of 17 generated by `sf::st_read` indicates the first problem there - the value from `osmdata` of 14 + 2 = 16 is correct here. The most important difference is that the Simple Features Standard, hence `GDAL` and also `sf` will only identify objects ("features") as polygons if they have numerically identical start and end points. OpenStreetMap does not work that way, and multipolygon objects can be specified by simply specifying member `"role"` values of `"inner"` or `"outer"` - those values flag that the objects are parts of a multi*polygon* rather than multi*line* object. Identical start and end points *may* be optionally specified in OSM, but that is not required, so if start and end points are not identical yet the object is a `multipolygon`, then the end of the final member must be joined onto start of the first member to constrct the final `multipolygon` (or starts and ends of sub-components with different roles must be joined, or whatever is appropriate for a particular `multiipolygon` specification). With the data as (currently) generated in that vignette example, there are only 2 `relation` objects which do not have members with `role = "outer"`, and so `osmdata` correctly returns 2 linestrings, while the remaining 14 are correctly designated as `multipolygon` objects. Importantly, `osmdata` correctly stitches the ends points of these together to ensure they comply with Simple Features, while neither `GDAL` nor therefore `sf` do this, and so they can only be designed (incorrectly here) as `multiline` objects. Does that make sense?

----

Thanks so much @agila5 for some very thoughtful and considered input - very much appreciated as always. Once you're happy with all of my responses and package tweaks, please feel free to close this issue.

**Comment by agila5** [comment]
Hi! 

> I'm not sure about that either, and what you see would indeed be correct if the points were not there ... but i also can not reproduce your output. When I run those lines, I see the points included in the output. I guess we can just hope that this was some kind of glitch on your side, and that when you re-run it you do indeed see the points there?

I can't reproduce that problem either so I don't know. Anyway it seems to be fine now!

> The above commit fixes that, so the c method now returns the osm_multilines object. I also updated all of the vignette output for the Sevilla examples.

Awesome, thanks. 

> I can't reproduce this, and now get the following output:

Me neither and now I get the same output as you obtained. I don't know what happened a few months ago.  

> Does that make sense?

Yup, thanks again for your really detailed explanation and that fix.
