### ISSUE TITLE
"No polygonal boundary" and "Unknown query clause" when using a polygon as bbox

### ISSUE THREAD

**Issue by stragu** [ropensci/osmdata#189]
I am trying to get data from inside an OSM multipolygon:

```r
library(osmdata)
uq2 <- getbb("University of Queensland", format_out = "polygon") %>% 
  opq() %>% 
  add_osm_feature(key = "building", value = "university") %>% 
  osmdata_sf()
```

... but I keep getting this error:

```
No polygonal boundary for University of Queensland
Request failed [400]. Retrying in 1.7 seconds...
Request failed [400]. Retrying in 1 seconds...
Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: line 3: parse error: Unknown query clause Error: line 4: parse error: Unknown query clause Error: line 5: parse error: Unknown query clause 
```

... even though the first result in the [Nominatim search](https://nominatim.openstreetmap.org/search.php?q=university+of+queensland) is [the multipolygon I am after](https://nominatim.openstreetmap.org/details.php?place_id=198973735).

Any idea why that is?

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.3   sf_0.8-0      tmap_2.3-1    osmdata_0.1.1

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5   purrr_0.3.2        lattice_0.20-38    htmltools_0.3.6   
 [5] viridisLite_0.3.0  yaml_2.2.0         XML_3.98-1.20      rlang_0.4.0       
 [9] e1071_1.7-2        later_0.8.0        pillar_1.4.2       glue_1.3.1        
[13] DBI_1.0.0          sp_1.3-1           RColorBrewer_1.1-2 stringr_1.4.0     
[17] rgeos_0.5-2        rvest_0.3.4        raster_3.0-7       htmlwidgets_1.3   
[21] leafsync_0.1.0     codetools_0.2-16   httpuv_1.5.2       crosstalk_1.0.0   
[25] curl_4.2           class_7.3-15       Rcpp_1.0.2         KernSmooth_2.23-16
[29] xtable_1.8-4       promises_1.0.1     classInt_0.4-1     lwgeom_0.1-7      
[33] leaflet_2.0.2      jsonlite_1.6       mime_0.7           packrat_0.5.0     
[37] digest_0.6.21      stringi_1.4.3      shiny_1.3.2        tmaptools_2.0-2   
[41] grid_3.6.1         rgdal_1.4-6        tools_3.6.1        magrittr_1.5      
[45] tibble_2.1.3       dichromat_2.0-0    crayon_1.3.4       pkgconfig_2.0.3   
[49] xml2_1.2.2         lubridate_1.7.4    assertthat_0.2.1   httr_1.4.1        
[53] rstudioapi_0.10    R6_2.4.0           units_0.6-4        compiler_3.6.1  
```

**Comment by mpadge** [comment]
@Robinlovelace I shoulda PR'ed this to ask you for a code review - sorry about that! But the above example from @stragu clearly indicates the need to expand our interpretation of `featuretype`. @stragu The reason this used to fail was because we'd hard-coded our understanding of what a bounding box `"featuretype"` was to various categories of settlement. The problem with your example arose in the second line of the [Nominatim search result](https://nominatim.openstreetmap.org/details.php?place_id=198973735), which clearly states `Type="amenity:university"`. Our previous restrictions did not allow for any `"featuretype"` other than `"settlement", "city", "county", "state", "country"`, so this was just not possible. The commit allows `"featuretype"` to be anything at all, so all you have do @stragu is specify `featuretype = "amenity:university"`, and you'll get your polygonal bbox returned.

And now my Q for you @Robinlovelace, as the original author of this code: Was there any reason to restrict `featuretype` to those previous values? None that i could see. We can simply pass any value of `"featuretype"` straight through to Nominatim, and it will just return nothing if it gets a nonsensical input. Up to the user, and allows flexibility to get what @stragu requires here, right?

**Comment by Robinlovelace** [comment]
Hi @mpadge, no reason to restrict the feature type. Looking at the history of the relevant file, I think that restriction was added in https://github.com/ropensci/osmdata/commit/a6ca5cb30540fbf36a7d72595a61f0d69419e729. This bit was the original implementation of that restriction, your code I think @mpadge:

https://github.com/ropensci/osmdata/blob/a6ca5cb30540fbf36a7d72595a61f0d69419e729/R/getbb.R#L136-L144 


No need for review in this case as it definitely fixes an issue, thanks @stragu for reporting it and @mpadge for the quick fix!

**Comment by stragu** [comment]
Just tried with the latest master, and I can confirm that it works! Thank you so much for the fastest response + fix I have ever seen, @Robinlovelace and @mpadge, very impressed! :)

One thing that is still bugging me is that the query grabs a bit more than it is supposed to, as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/1747497/67737595-81e6dc00-fa57-11e9-8817-7c5f1f66861f.png)

I don't understand why, as the polygon used as a bounding box looks like expected:

```r
getbb("University of Queensland", format_out = "sf_polygon",
      featuretype = "amenity:university") %>% plot()
```

![image](https://user-images.githubusercontent.com/1747497/67737694-f91c7000-fa57-11e9-8d4d-7821a94fb5ec.png)

Does the Overpass query get simplified somehow?

**Comment by Robinlovelace** [comment]
**osmdata** passes a rectangular bounding box to the api. You could do a spatial subset to return all features that intersect with the polygon, as described here for example: https://geocompr.robinlovelace.net/spatial-operations.html#spatial-subsetting

**Comment by mpadge** [comment]
The data are identical. Here's a zoom-in on the roundabout from Nominatim:
![image](https://user-images.githubusercontent.com/6697851/67749212-f9ebdc80-fa2c-11e9-85e6-ce90a27c2e19.png)
and here is the `osmdata` result, processed with these lines:
``` r
bb <- getbb("University of Queensland", format_out = "polygon",
      featuretype = "amenity:university")
library (sf)
bp <- st_polygon (list (bb [[1]])) %>%
    st_sfc (crs = 4326) %>%
    st_sf ()
library (mapdeck)
set_token (Sys.getenv ("MAPBOX_TOKEN"))
mapdeck (style = 'mapbox://styles/mapbox/dark-v9') %>%
    add_polygon (data = bp, stroke_colour = "FFCC22", stroke_width = 2,
                 fill_colour = "#EEFF9922")
```
![image](https://user-images.githubusercontent.com/6697851/67749354-48997680-fa2d-11e9-8ad0-5561423053a7.png)

The only differences there are rendering interpretations - should a line be drawn in the middle, to the outside, or to the inside of the specified coordinates? (At it looks like Nominatim uses a renderer that draws outlines just beyond the bounding coordinates of a polygon, while `deck.gl`, the engine for [`mapdeck`](https://github.com/SymbolixAU/mapdeck), draws the outlines to be just contained by the bounding coordinates.)

I presume in your screenshot above that you're referring to the few extra building across the other side of the river - I've no idea what code you may have used to specify which were "within" the polygon, but at least it is important to consider that OSM data are spheroidal (CRS 4326 = WGS84), and so need to be re-projected to some planar form in order to accurately perform geometrical calculations.

**Comment by stragu** [comment]
Thanks again for the replies. It is starting to make more sense!

So, to be clear, is this:

```r
uq <- getbb("University of Queensland",
            featuretype = "amenity:university") %>% 
  opq() %>% 
  add_osm_feature(key = "building") %>% 
  osmdata_sf()
```
... completely equivalent to this:

```r
uq <- getbb("University of Queensland",  format_out = "polygon",
            featuretype = "amenity:university") %>% 
  opq() %>% 
  add_osm_feature(key = "building") %>% 
  osmdata_sf()
```
... both creating a query with the same rectangular bounding box?

If that is the case, how come the `opq()` help page says the following:

> "`bbox` [...]  Can also be (iii) a matrix representing a bounding polygon as returned from getbb(..., format_out = "polygon")."

I suspect many users will expect this third option to only return features that are located _inside_ the polygon, instead of inside a rectangular bounding box that _contains_ the "bounding polygon".

Anyway, I managed to do what I was hoping for with the following:

```r
#get features
uq <- getbb("University of Queensland", format_out = "polygon",
            featuretype = "amenity:university") %>% 
  opq() %>% 
  add_osm_feature(key = "building") %>% 
  osmdata_sf()

# get bounding polygon
uq_poly <- getbb("University of Queensland", format_out = "sf_polygon",
      featuretype = "amenity:university")

# get polygons out
library(dplyr)
library(sf)
poly <- uq$osm_polygons %>% 
  filter(!is.na(building)) %>% 
  # only keep buildings inside the UQ polygon
  st_intersection(uq_poly)
# get multipolygons out
mp <- uq$osm_multipolygons

# view of polygons works
library(tmap)
tmap_mode("view")
tm_shape(poly) +
  tm_polygons()

# view of multipolygons fails
tm_shape(mp) +
  tm_polygons()

# workaround: remove names from multipolygons
# ref: https://github.com/mtennekes/tmap/issues/360#issuecomment-546872793
for(i in seq(nrow(mp))) {
  names(mp$geometry[[i]][[1]]) = NULL 
}

# merge all buildings
# ref: https://github.com/r-spatial/sf/issues/798#issuecomment-405157853
buildings <- st_as_sf(data.table::rbindlist(list(poly, st_cast(mp, "POLYGON")), fill = TRUE))

# view it
tm_shape(buildings) +
  tm_polygons("building",
              id = "name",
              popup.vars = c("alt_name", "ref")) +
  tm_basemap(server = "CartoDB.PositronNoLabels")
```

**Comment by stragu** [comment]
Great, thank you @mpadge , didn't know this one existed.
I noticed something odd with `trim_osmdata()`, but I'll stop using this issue to narrate my whole process - I'll nag you in a new issue! :)
Cheers
