### ISSUE TITLE
Road width, lane number, maximum speed, capacity using osmdata package

### ISSUE THREAD

**Issue by khzannat26** [ropensci/osmdata#214]
I am using osmdata package to download roadway feature, road width, lane number, maximum speed. I am trying to import the OSM data in MATSim. My written code is:
library (osmdata)
q <- opq(bbox = 'Dhaka')%>%
  add_osm_feature(key = "highway",value = c("motorway","primary","tertiary"))
motorway <- osmdata_xml(q)
How can I download road width, lane number maximum capacity using osmdata package?

**Comment by Robinlovelace** [comment]
Good question. You have already downloaded the available major road data by the looks of it, and it may be that the variables you want are not (yet) in OSM for that part of the world. Have you checked the data carefully in the case study area by identifying features whilst zoomed into a specific road at https://www.osm.org ?

Also this vignette https://docs.ropensci.org/osmdata/articles/osmdata.html and the transport chapter in the open source book Geocomputation with R may help with your work. I think skilling-up your general R skills will also help and there are plenty of resources out there to help.

**Comment by mpadge** [comment]
To only slightly expand upon the useful answer of @Robinlovelace, whether or not these attributes are present in a particular data set is largely dependent on local mapping cultures - some places tend to do comprehensive mapping of as many attributes as possible, while others might only map geometries and leave these elements mostly empty. The particular features you want can be examined via the [`available_tags()`](https://docs.ropensci.org/osmdata/reference/available_tags.html) function, or directly via the [OSM wiki](https://wiki.openstreetmap.org). If you use the [`osmdata_sf()` function](https://docs.ropensci.org/osmdata/reference/osmdata_sf.html), the `keys` will be columns, with each row holding a `value`. So there should be a `width` column with values for each segment.

Local practices often also conform to a common understanding of "standard' widths or maximum speeds, and only specify values where they deviate from these. Such "standard" widths or speeds might not be explicitly specified, in which cases most values in a column may be `NA`, but you could infer them by examining distributions from values that are specified, and perhaps presuming mean values to approximate standard values where not otherwise specified.

Feel free to ask any further questions if anything is not clear, but I'll close in the meantime. Thanks for using; thanks for asking!
