### ISSUE TITLE
Feature request: Download only a certain type of feature

### ISSUE THREAD

**Issue by gdkrmr** [ropensci/osmdata#221]
Sometimes I only want, e.g., points but the query also returns many areas or lines and takes longer than necessary or even times out.

It wold be great if it would be possible to limit the query to single feature type.

**Comment by mpadge** [comment]
Thanks for the query, but you'd need to provide more information, importantly including a concrete use case, for me to be able to appreciate what you're requesting. I suspect the general answer is going to be that what you're requesting is not generally possible because OSM is not built that way. A "feature" in OSM is one of the things listed in the output of `available_features()`, whereas a "feature" in Simple Features terminology is quite different. The `osmdata_sf()` function attempts to reconcile these two by mapping OSM "features" onto `sf` "features". This is not trivial, as explained in [this vignette](https://docs.ropensci.org/osmdata/articles/osm-sf-translation.html).

OSM is built around *relationships* between *nodes*, *ways*, and *relations*. It seems that what you're asking for is a way to access *nodes* only. This only makes sense for specific requests which are very strictly point-based, such as traffic lights or drinking fountains, for which the functionality as it exists will work perfectly, and will not download any unnecessary data. For most data sets, the points returned in an `osmdata_sf` structure include all points which make up all ways and relations, and the only way to extract these is to get those ways and relations within the query.

You can always modify the actual query string passed to the overpass server yourself and try it out. If, for example, you do some `opq(...) %>% add_osm_feature(key = "highway")`, and then use `opq_string()` to get the query and remove the bits requesting the `way` and `relation` components, then you will get no data, because a `key = "highway"` feature is a `way`, and not a `node`. Two points in conclusion:

1. In general, such queries would make no sense, because that's not the way OSM itself is built; if you want the points of some OSM object of finite extent, then you have to request that entire object in order to extract the points, so you need all `way` and `relation` information anyway.
2. It is not possible for any query to "take longer than necessary" - the interface to overpass is constructed to extract the absolute minimal necessary data for a given query. You can do everything you want by designing more specific queries, including using the `c` method for `osmdata` objects to join results of multiple queries, and in extreme cases by modifying the actual query passed directly to overpass via the `opq_string` function.

Feel free to re-open if you can provide a particular use case that takes note of the above, and that includes full code to demonstrate what you're requesting, and that has been generated by using [`reprex`](https://reprex.tidyverse.org/).

**Comment by gdkrmr** [comment]
Thanks for your long answer, and sorry for not providing an example earlier. Here is my use case:

```R
'node[place="city"]
 (49.999667, 9.999889, 55.00000, 15.00022);
 out;' %>%
  osmdata_sf()

c(9.999889, 49.999667, 15.00022, 55.00000) %>%
  opq %>%
  add_osm_feature("place", "city") %>%
  osmdata_sf
```

The first one works fine for me, the second one gets me a timeout almost always, even if I increase the timeout, because it also queries all the city borders. The query looks like this:

```
[out:xml][timeout:25];
(
 node  ["place"="city"] (49.999667,9.999889,55,15.00022);
 way  ["place"="city"] (49.999667,9.999889,55,15.00022);
 relation  ["place"="city"] (49.999667,9.999889,55,15.00022);
);
(._;>;);
out body;> 
```

Not sure if this satisfies your requirements and if it would make sense to include such a feature in `osmdata`.

**Comment by mpadge** [comment]
Okay, now i see, and am happy to reopen to address this

**Comment by mpadge** [comment]
@gdkrmr Thanks for the great idea. The above commit now makes the following possible, via a `nodes_only` parameter to `opq()`:
``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
bbox <- c (10, 50, 15, 55)
x <- opq (bbox, nodes_only = TRUE) %>%
    add_osm_feature (key = "place", value = "city") %>%
    osmdata_sf (quiet = FALSE)
#> Issuing query to Overpass API ...
#> Rate limit: 2
#> Query complete!
#> converting OSM data to sf format
x
#> Object of class 'osmdata' with:
#>                  $bbox : 50,10,55,15
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 22 points
#>             $osm_lines : NULL
#>          $osm_polygons : 'sf' Simple Features Collection with 0 polygons
#>        $osm_multilines : NULL
#>     $osm_multipolygons : NULL
```

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think it's worthwhile implementing any extensions like `ways_only`, because anyone extracting ways is going to want relations anyway. Even relations can be important for node-only data, and are *not* returned by setting `nodes_only = TRUE`, but your use case is a great example of how this feature is nevertheless useful. Thanks for the input!
