### ISSUE TITLE
HTTPS certificate has expired

### ISSUE THREAD

**Issue by robitalec** [ropensci/osmdata#224]
Just a heads up, this has been reported here: https://github.com/drolbr/Overpass-API/issues/579

In `osmdata` the error looks something like this:

```r
library(osmdata)
opq('Quebec') %>% 
  add_osm_feature(key = 'administrative', 'boundary') %>% 
  osmdata_sf()
```

```
Error in curl::curl_fetch_memory(url, handle = handle): SSL certificate problem: certificate has expired
Request failed [ERROR]. Retrying in 2 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): SSL certificate problem: certificate has expired
Request failed [ERROR]. Retrying in 3.4 seconds...
```

**Comment by matkoniecz** [comment]
It is working again.

**Comment by robitalec** [comment]
Apologies, it has been resolved (quickly!)

**Comment by matkoniecz** [comment]
I did the same at https://github.com/westnordost/StreetComplete/issues/1898 :)

**Comment by mpadge** [comment]
Thanks for reporting, and great to see it fixed itself.

**Comment by espinielli** [comment]
Is it only me or this is happening again?

**Comment by mpadge** [comment]
It was (has been / is / ...?) happening on  some systems due to general [expiration of root certificates](https://letsencrypt.org/2021/10/01/cert-chaining-help.html) that will fix itself once servers and OS update their certificate stores. Nothing to worry about, and nothing to do except wait if you're still encountering problems.
