### ISSUE TITLE
Import xlm files 

### ISSUE THREAD

**Issue by orlandombaa** [ropensci/osmdata#226]
Hi

I have been using the library to download osm data. However,  I already have xlm files for a given area. I have not found a way to import these file directly from my computer using OSMDATA library. 
is this possible? 

thank you.,

**Comment by orlandoandradeb** [comment]
Hello @mpadge , sorry I wrote it wrong. I have files in format XML that I would like to import directly to R from files on my computer. 
That reason is that I want to modify the files and run modelling scrips routing.  However, as I mentioned previously I have not found a way with the library OSMDATA which at the moment just allows me to download data via a request directly to OSM.

**Comment by mpadge** [comment]
Oh, okay, then what you want is the `doc` argument of the `somdata_s*()` functions (see, for example, [`osmdata_sf()`](https://docs.ropensci.org/osmdata/reference/osmdata_sf.html)). That function expects a query (`q`) that was used to extract the data, but you can use it without, and it'll just give you a warning yet still load the data. Let me know how that goes
