### ISSUE TITLE
feature(import): read and filter externaly downloaded xml_osm files

### ISSUE THREAD

**Issue by ec-nebi** [ropensci/osmdata#261]
Request: I download some OSM data from geofabrik. I filter and import them R with `osmdata_sf`. 

This works great if you go through the turbo-overpass API via osmdata. However, this requires internet (it is not ubiquitous nor fast everywhere, and consume a lot of energy)

This feature would enable to use already downloaded data.

The following example show how it works with turbo-overpass but fails when files are downloaded with anotherservice such as "overpass.openstreetmap"
``` r
library(sf)
library(osmdata)

 # Via TURBO API works fine. Thanks!
 q <- opq(bbox = c(-0.12, 51.51, -0.11, 51.52)) %>%
    add_osm_feature(key = 'landuse')
 doc <- osmdata_xml(q, "landuse.osm")
 dat1 <- osmdata_sf(q, doc)
 dat2 <- osmdata_sf(q, "landuse.osm")

 # External Download, don't (expecting Debian based system with curl)
 file_osm <- "landuse2.osm"
 bbx <- c(-0.12, 51.51, -0.11, 51.52)
 # curl call to overpass
 overpass <- paste0("http://overpass.openstreetmap.ru/",
                    "cgi/xapi_meta?*","\\[bbox=",
                    paste0(bbx,collapse=","), "\\]")
 curl_call <- paste("curl -o", file_osm, shQuote(overpass))
 print(curl_call)
 #  [1] "curl -o landuse2.osm 'http://overpass.openstreetmap.ru/cgi/xapi_meta?*\\[bbox=-0.12,51.51,-0.11,51.52\\]'"
 
# Next line : sanity check the call before removing "#". The file should be around 5.4 M
# system(curl_call) 
 dat3 <- osmdata_sf(q, "landuse2.osm")
#> Error in rcpp_osmdata_sf(doc) : std::bad_alloc
 dat3_polygons <- st_read("landuse2.osm", layer = "multipolygons")

```

I am not sure if this is a bug or a feature. If this is a Feature, I would make it clearer in the vignette, that only download with `osmdata` package will work. What is not so great with st_read is the way OSM data are read depends of the config (see Robin's comment [#sf/issues/1157](https://github.com/r-spatial/sf/issues/1157#issuecomment-535872421)).

I don't know if osmdata usr [osmfilter](https://wiki.openstreetmap.org/wiki/Osmfilter). I tested stupid call such as 

```r
system("osmfilter landuse2.osm --keep=landuse -o=landuse_filtered.osm")
dat4 <- st_read("landuse_filtered.osm", layer ="multipolygons")

```

It works, but I don not know if it helps. Sorry!

Thanks! :smile:

**Comment by mpadge** [comment]
Thanks @ec-nebi, that's an interesting observation. The `osmdata` package was conceived of as nothing more than an interface to the overpass API, so was never intended to be able to process direct downloads. The main reason is that all functions return rectangular objects with one column for each key present. Requiring users to specify at least one key-value pair is the only way to restrict numbers of columns to some sane and sensible number. In your case, that error is because the routines are trying to construct multiple arrays with some arbitrarily huge number of columns.

The data are nevertheless identical in form, just with overpass versions pre-filtered to some sensible (effective) number of columns, whereas direct downloads aren't I guess we could intercept the code somewhere around the point where numbers of columns are estimated, and dump an error message to suggest the need to specify key-value pairs, and/or use `overpass` to do so.

I definitely intend to bundle the core `osmium` routines at some stage into a separate package, and that will enable arbitrary pre-filtering of bulk data like that. Until then, I doubt that anything more than sensible error messages will be implemented here. Happy to hear any further insights you might have into how to deal with these kinds of situations.

**Comment by ec-nebi** [comment]
Thank for the feedback. I still don't understand the details but I have the impression that it is not related to your assumption: "The main reason is that all functions return rectangular objects with one column for each key present. Requiring users to specify at least one key-value pair is the only way to restrict numbers of columns to some sane and sensible number. In your case, that error is because the routines are trying to construct multiple arrays with some arbitrarily huge number of columns."

```r
# I query with osmdata without key nor value
bbx <- c(-0.12, 51.51, -0.11, 51.52)
q <- opq(bbox = bbx)
file_doc <- "unfeatured.osm"
doc <- osmdata_xml(q, file_doc)
dat1 <- osmdata_sf(q, doc)
dat1$osm_multipolygons[,"osm_id"]

# I query directly overpassapi without key nor value
overpass <- paste0("https://overpass-api.de/api/interpreter?nwr(",
                    paste0(bbx[c(2,1,4,3)],collapse=","),");out;")
file_osm_overpass <- "unfeatured_curled.osm"
curl_overpass <- paste("curl -o", file_osm_overpass, shQuote(overpass))
print(curl_overpass)
# system(curl_overpass) # Check call before uncommenting
dat2 <- osmdata_sf(q, file_osm_overpass)
# Error
dat2 <-st_read(file_osm_overpass, layer="multipolygons")

file.size(file_doc, file_osm_overpass)/2^10/1000
# ca 18.06  4.00 MB

# But
plot( dat1$osm_multipolygons[,"osm_id"] )
# All polygons are not topological valid
plot(dat2[st_is_valid(dat2),"osm_id"])
# although for dat1 too 
table(st_is_valid(dat1$osm_multipolygons))

```

Not that I correct the API (in my previous example I was using the older xapi). I though that turbo-overpass was only a friendly interface to the Overpass API. I will think further about it... :thinking: :sunglasses: (I am new to OSM querying)

**Comment by mpadge** [comment]
@ec-nebi There was indeed a bug leading to the original error you observed. The above commit fixes it, and you should now see this:
``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
packageVersion ("osmdata")
#> [1] '0.1.8.13'
q <- opq(bbox = c(-0.12, 51.51, -0.11, 51.52)) %>%
        add_osm_feature(key = 'landuse')
file_osm <- "landuse2.osm"
bbx <- c(-0.12, 51.51, -0.11, 51.52)
# curl call to overpass
overpass <- paste0("http://overpass.openstreetmap.ru/",
                   "cgi/xapi_meta?*","\\[bbox=",
                   paste0(bbx,collapse=","), "\\]")
curl_call <- paste("curl -o", file_osm, shQuote(overpass))
system (curl_call)
dat3 <- osmdata_sf(q, "landuse2.osm")
#> Error in rcpp_osmdata_sf(doc): way can not be found
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

That is the expected response because the query is mal-formed for processing by the `osmdata` package. This package needs, and therefore expects, a data set to include full data on all `way` members of all `relations`, and on all `node` members of all `ways`. That requires the [Overpass Recurse Up operator](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_up_.28.3C.29), demonstrated in the second of the following examples:

``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
packageVersion ("osmdata")
#> [1] '0.1.8.13'
q <- opq(bbox = c(-0.12, 51.51, -0.11, 51.52)) %>%
        add_osm_feature(key = 'landuse')
file_osm <- "landuse2.osm"
bbx <- c(-0.12, 51.519, -0.119, 51.52)
overpass <- paste0("https://overpass-api.de/api/interpreter?nwr(",
                   paste0(bbx[c(2,1,4,3)],collapse=","),");out;")
print (overpass)
#> [1] "https://overpass-api.de/api/interpreter?nwr(51.519,-0.12,51.52,-0.119);out;"
curl_call <- paste("curl -o", file_osm, shQuote(overpass))
system (curl_call)
osmdata_sf(q, "landuse2.osm")
#> Error in rcpp_osmdata_sf(doc): node can not be found

overpass <- paste0("https://overpass-api.de/api/interpreter?nwr(",
                   paste0(bbx[c(2,1,4,3)],collapse=","),");(._;>;);out;")
print (overpass)
#> [1] "https://overpass-api.de/api/interpreter?nwr(51.519,-0.12,51.52,-0.119);(._;>;);out;"
curl_call <- paste("curl -o", file_osm, shQuote(overpass))
system (curl_call)
osmdata_sf(q, "landuse2.osm")
#> Object of class 'osmdata' with:
#>                  $bbox : 51.51,-0.12,51.52,-0.11
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 10648 points
#>             $osm_lines : 'sf' Simple Features Collection with 2265 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 40 polygons
#>        $osm_multilines : 'sf' Simple Features Collection with 30 multilinestrings
#>     $osm_multipolygons : 'sf' Simple Features Collection with 1 multipolygons
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

As long as you form queries correctly, the package will be able to process arbitrary input files. Note that the output data include all information on the OSM relation, way, and node IDs, and so enable all of the hierarchical inter-relationships present in the data to be traced and analysed. These are all "hidden" as list item and rownames of the spatial matrices embedded within the "geometry" columns of the `sf` data. Reading the same data into R via any other method which relies on GDAL (so `sf` or `osmextract`) strip all of these data, reducing everything to geographic coordinates only.

**Comment by ec-nebi** [comment]
Nice explanation and thank you for providing an alternative to GDAL to read OSM data in R. I like it! :milky_way:  :package:
