### ISSUE TITLE
Error in rcpp_osmdata_sf

### ISSUE THREAD

**Issue by stalkerGH** [ropensci/osmdata#336]
I got a message during making a query: _Error in rcpp_osmdata_sf(paste0(doc)) : 'names' attribute must be the same length as the vector_ Next error after this is the same as in my other issue report: https://github.com/ropensci/osmdata/issues/335

How can I debug that?

PS. How to disable 'quiet' in osmdata to have maximum level of debug information?

**Comment by mpadge** [comment]
To have any chance of debugging that, we're going to need a fully reproducible example, which will mean requesting data from the Kumi server with the usual workflow. If you can provide that, we'll be happy to help more. That error message does indeed seem indicative of a bug, but that may in this case be due to server misconfiguration, so a full example will be needed, constructed with [the `reprex` package](https://reprex.tidyverse.org/). Thanks!

**Comment by stalkerGH** [comment]
Probably self-resolved. I close the issue.
