### ISSUE TITLE
Select region by polygon (instead of bbox)

### ISSUE THREAD

**Issue by sytpp** [ropensci/osmdata#80]
I would like to extract the features within a city boundary, e.g. the City of London.

At the moment the `opq(bbox)` to query overpass only excepts a bounding box or translates a string query into a bounding box.  

```
> q <- opq(bbox = "city of london uk")
> q
$bbox
[1] "51.5068696,-0.1138211,51.5233213,-0.0727261"
```

This results in plots like this:

![screen shot 2017-07-06 at 15 50 08](https://user-images.githubusercontent.com/8035937/27917098-ebc5d3a4-6262-11e7-8585-abe760a5e9ad.png)

However, I would like to have all the features overlapping with the arbitrary polygon of the city than the bounding box around it. Overpass API allows for this with [Select Region by Polygon](http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Select_region_by_polygon). Would be great to realise that in osmdata as well!

P.S.: A related issue: Quering Overpass with a bbox returns all the features, which overlap with the bbox and they may extend beyond it (see picture). Is there a way to make a "clean" cut and an only return the part of the feature (line or polygon), which is strictly inside the bbox?

**Comment by mpadge** [comment]
This is a fantastic idea! Thanks for the incentive Sylvia!

**Comment by mpadge** [comment]
@Robinlovelace I've just modified your brilliant `getbb` function to enable it to extract polygonal bounding boxes [with this commit](https://github.com/ropensci/osmdata/commit/cf434a296cae979bcf33a3660a2a4f5d3c6317e7). Can you please have a look and give feedback? In particular, I've set some arguably arbitrary default behaviour. Note that `nominatim` returns potentially multiple polygons for the same location, "london uk" being a fine example which gives a large, enclosing polygon for greater London, and a smaller, enclosed polygon for the City. Thus each match returns a list of one or more items, so multiple matches will be returned as lists of lists.

My default behaviour is:
1. Where multiple matches arise ("london" absent specification, for example), just return all lists of lists of polygons
2. But where one a single match arises ("london uk"), just return the first list item ("greater london") as a single matrix.

My presumption is the the latter will usually be what people want, and it'll enable simple textual refinement of a query to eventually return a simple matrix, rather than trawling through lists of lists of matrices, while leaving flexibility to do the latter if desired/required.

(This could also be done cleaner using `geojson` functionality, because nominatim can also return `geojson` polygons, but as you know i'm a lean-dependency freak and so have done it base-R. Whatever.)

Now try to break it!

cc @mtennekes, and note to whom: Our `bbox` function has no projection because we're working entirely with OSM data, and the projection is handled elsewhere. Nominatim fortunately uses the same projection, so the `bbox` (which is no longer strictly a box) can be a simple list of coordinates. Handy for us, not so good for your swiss army knife version.

**Comment by mpadge** [comment]
@sytpp The overpass select-by-polygon turns out not to actually be usable here (it's restricted to extracting points only), but i think I've now implemented a good solution. Because all data have to be downloaded in rectangular bounding boxes, I've left that functionality as it was, but implemented extraction of bounding polygons along with a `trim_osmdata()` function to trim data within the polygon. This is all now possible on current dev version:
```{r}
library (magrittr)
dath <- opq ('city of london uk') %>% add_feature (key = 'highway') %>%
    osmdata_sf (quiet = FALSE)
datg <- opq ('city of london uk') %>%
    add_feature (key = 'leisure', value = 'park') %>%
    osmdata_sf (quiet = FALSE)
bb <- getbb ('city of london uk')
```
Plot the basic map:
```
library (osmplotr)
map <- osm_basemap (bbox = bb, bg = "gray95") %>%
    add_osm_objects (dath$osm_lines, col = "gray50") %>%
    add_osm_objects (datg$osm_polygons, col = "lightgreen") %>%
    print_osm_map ()
```
![map1](https://user-images.githubusercontent.com/6697851/28113055-73541384-66fb-11e7-8e20-4227c80adfb1.png)

(Note that the `osmplotr` function `print_osm_map()` adjusts the map to the `bbox`, so excludes all the stray highways which appear in your plot.)

Then simply trim the data using `exclude = FALSE` which will **include** any and objects partially extending into the bounding polygon
```
dath <- trim_osmdata (dath, bb_poly, exclude = FALSE)
datg <- trim_osmdata (datg, bb_poly, exclude = FALSE)
```
and plot again using same code as above:
![map1](https://user-images.githubusercontent.com/6697851/28113176-d3de591c-66fb-11e7-92b4-3c64ebc8dc04.png)

Or trim **exclusively** within the bounding polygon
```
dath <- trim_osmdata (dath, bb_poly, exclude = TRUE)
datg <- trim_osmdata (datg, bb_poly, exclude = TRUE)
```
![map1](https://user-images.githubusercontent.com/6697851/28113211-f4e2bd38-66fb-11e7-96ed-226552742c1c.png)

(and hey, it seems like the City of London boundary extends across Blackfriars Bridge. Interesting.)

There you go. I really like this functionality; thanks so much for motivating it! Now I'll just wait to see if @Robinlovelace can break the code (which is likely; he's really good at that) before closing ...

**Comment by mpadge** [comment]
Plus this has to be described in the vignette before closing

**Comment by Robinlovelace** [comment]
I've not exactly broken it but I have found that it returns lists within lists - too much to document in the example but will put in a PR showing that it's a list if the search returns more than 1 place:

``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
bb <- getbb("london", format_out = "polygon")
length(bb)
#> [1] 5
sapply(bb, length)
#> [1]   2 970   5  24   2
par(mfrow = c(3, 3))
plot(bb[[1]][[1]])
plot(bb[[1]][[2]])
plot(bb[[2]][[1]])
plot(bb[[3]][[1]])
plot(bb[[4]][[1]])
plot(bb[[5]][[1]])
par(mfrow = c(1, 1))
```

![](http://i.imgur.com/1Jx8hEd.png)

``` r
bbmat = matrix(unlist(bb), ncol = 2)
plot(bbmat)
```

![](http://i.imgur.com/ERsgfIz.png)

**Comment by Robinlovelace** [comment]
Yes I broke it (or have highlighted where I think your code broke `format_out = "data.frame"`):

```
getbb(place_name, format_out = "data.frame", limit = 3)
Error in getbb(place_name, format_out = "data.frame", limit = 3) : 
  format_out not recognised; please specify one of [data.frame, matrix, string, polygon]
```

**Comment by mpadge** [comment]
The lists within lists was intentional as described above, although I'm not exactly sure that's the best solution. Overpass returns (effectively) lists of polygons, but where one or more of those are entirely contained within others, each list item is itself a list. So the lists of lists is the natural form; I just opted to simplify cases where there is only one initial list, for which I simply selected the first item. Better suggestions appreciated!

**Comment by Robinlovelace** [comment]
That makes sense. Plan to say that in the vignette PR>

**Comment by mpadge** [comment]
[This commit](https://github.com/ropensci/osmdata/commit/a6ca5cb30540fbf36a7d72595a61f0d69419e729) adds extra `featuretype` values to `getbb()` for more precise specification of "city", "county", "state", or "country". This also needs to be documented in the vignette. A good example following #87 is "madrid" which is a city, an internal admin district, and a county.

cc @Robinlovelace

**Comment by Robinlovelace** [comment]
I think we should also add a function that convert the extracted polygons to spatial (`sf` in the first instance) form.

**Comment by mpadge** [comment]
[This commit](https://github.com/ropensci/osmdata/commit/dac4eb17ab080df1cea58d09c33d7457a5e4a073) gives the ability to pass bounding polygons direct to `opq()`, which is clearly necessary. (See #87 for examples.) @Robinlovelace I agree, especially once we implement default plotting in #77, but let's first decide how and where. `getbb()` already has `format_out` which can be one of `"matrix", "string", "data.frame", "polygon"`, so this parameter isn't really set to be overloaded with additional polygon options. I guess we'd then need an additional parameter in `getbb()` (`"poly_format"`?) with options like `"matrix", "sp", "sf"`? That would be pretty easy, and then we'd just have to modify `opq()` to recognise and parse the different possible formats. What do you think?

**Comment by Robinlovelace** [comment]
I meant a separate function that converts the output of `format_out = "polygon"` into an object of class sf. Once that exists adding another argument (e.g. `"sf"`) would be easy. But agree not a priority in any case.

**Comment by mpadge** [comment]
That separate function is simply `sf` (or `sp`, or whatever). Conversion of matrices is easy once you've got them. Let's just deal with the mess of other issues first and potentially come back to this sub-issue later.

**Comment by Robinlovelace** [comment]
Great fix - should've been me.
