### ISSUE TITLE
trim_osmdata removing features rather than cropping

### ISSUE THREAD

**Issue by sytpp** [ropensci/osmdata#94]
I've played a bit with the trim_osmdata function and noticed that the function does not do what the name suggests. Instead of 'trimming' the Simple Features to the polygon, it actually removes the features which extend beyond the polygon boundaries entirely. Here is an example:

```
cityName = "city of london"
key = "highway"
value = "."

q <- opq(bbox = cityName)
q <- add_osm_feature(q, key=key, value=value, key_exact = FALSE, value_exact = FALSE, match_case = FALSE)
streets <- osmdata_sf(q)

# in this case I am using the bounding box (as polygon) as 'border'
bb_matrix <- getbb(cityName, format_out = 'matrix')
bb_poly <- as.matrix(expand.grid(bb_matrix["x",], bb_matrix["y",]))[c(1,2,4,3),]
streets_bb <- trim_osmdata(streets, bb_2_poly(bb_matrix), exclude=T)
```
Comparing `streets`  and `streets_bb`: `streets` has 4823 linestrings and `streets_bb` has only 4662 linestrings. Since I extracted the geometry to overlap with exactly the same polygon (bb) I would expect them to have the same number of linestrings. It doesn't make much of a difference visually but if I wanted to calculate the length of the streets in a certain polygon, that would be misleading. 

I think, a function the would return something like an intersection between the bounding polygon and the simple features, i.e. actually trimming the features at the edge of the polygon, would be useful.

**Comment by mpadge** [comment]
"Trim" is a perfectly accurate term; it's merely not a geometric operation, rather it's a trimming of the underlying data. The `osmdata` package really is about the these data, and does not nor will not implement any operations which modify these data. Geometrically trimming the linestrings, polygons, or whatever would modify the data so that they no longer reflect what OSM actually represents. Moreover, there's no trivial way to do this. Consider a line that curves out beyond a polygon before curving back within. There's no answer to how this might best be "trimmed". Break into 2 lines? Join the two points lying just inside the polygon? Artificially insert two new points precisely on the polygon boundary? Whatever the answer, the underlying data would have to be modified, resulting in a representation that would differ from the underlying OSM data.

It would nevertheless be fairly easy to implement this by adapting the code in [`trim_osmdata`](https://github.com/ropensci/osmdata/blob/master/R/trim-osmdata.R), replacing `get_trim_indx()` with a function that returns the list of points included in polygon instead of binary `T/F` values. This should work okay straight up for lines, but polygons will likely break because of potentially invalid geometries.
