### ISSUE TITLE
Timeout, memsize, and scientific notation

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#97]
With the last round of commits, a few issues have appeared when querying for points of interests.
The most macroscopic one to me is the danger that was introduced in leaving the `timeout` and `memsize` settings up to the user (I have to admit that I ignore how it was managed before).

In fact, unless `options(scipen=999)` is set, providing large `timeout` and `memsize` values will render these numbers with scientific notation inside the overpass query list (thus introducing non-numeric characters), displeasing Overpass itself.

```
Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: line 1: parse error: ']' expected - '+' found. Error: line 1: parse error: ']' expected - '+' found. 
```

**Comment by mpadge** [comment]
Wow, you really are paying attention here! I'm impressed. And you've got a really good point that's hopefully been fixed with [this commit](https://github.com/ropensci/osmdata/commit/e12a03e43b8d498f3e317c729acdf376a0438b73). It's potentially dangerous to allow users to mess with these values, so they won't be written in the vignette or anything, but it's also very useful for large queries, and overpass allows it, so there's no real reason for `osmdata` not to also allow it.

**Comment by mpadge** [comment]
@richardbeare FYI: `osmdata` now enables explicit specification of timeout and memory size of overpass server. Just load the `dev` version and checkout `?opq`
